# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "hashicorp/precise64"    
    #ubuntu.vm.provision :shell, path: "install_apache.sh"
    ubuntu.vm.provision "ansible" do |ansible|
      ansible.playbook = "../Ansible/bootstrap.yml"
      ansible.sudo = true
      #ansible.verbose = "-v"
    end
    ubuntu.vm.network "public_network"
  end
  
  #config.vm.define "ws2012" do |ws2012|
  #  ws2012.vm.box = "kensykora/windows_2012_r2_standard"
  #  ws2012.vm.provision :shell, path: "install_chocolatey.cmd"
  #end	
end
