---
- name: change root password
  user:
    name=root
    password={{ root_password }} #ansible
    
- name: Create mattermost directory
  file: 
    path={{ mattermost_path }}
    state=directory
    owner=root
   
- name: download and install mattermost
  unarchive:
    src=https://github.com/mattermost/platform/archive/v2.2.0.tar.gz
    dest={{ mattermost_path }}
    copy=no
    
- name: Create mattermost data directory
  file: 
    path={{ mattermost_installation_path }}/data
    state=directory    
    
- name: edit mattermost driver db
  lineinfile:
    dest={{ mattermost_config_path }}/config.json
    regexp='"DriverName"{{ ':' }} "mysql",'
    line='        "DriverName"{{ ':' }} "postgres",'

- name: edit datasource db
  lineinfile:
    dest={{ mattermost_config_path }}/config.json
    regexp='"DataSource"{{ ':' }}'
    line='        "DataSource"{{ ':' }} "postgres://mmuser:mmuser_password@10.0.0.1:5432/mattermost?sslmode=disable&connect_timeout=10",'

 